### PR TITLE
ClientJS:Execute <script> after refreshing the DOM

### PR DESCRIPTION
**Pull request by kevinresol**
#23

I only tested it on Chrome and scripts was executed nicely.

### CODE REVIEW

**Comment by kevinresol** [comment]
I think there are some glitches for this method. I got some functionalities not (or occasionally) working when the pages are refreshed by the js client. Particularly, I am using UIkit. After refreshing, the nav bar dropdown just won't show (but it *sometimes* shows again when the page refreshed again). 

Need some ways to thoroughly test this. Any ideas?

**Comment by MichaPooh** [comment]
I've got the same glitches with this method. 
As a (hacky) workaround I gave the script tag an id attribute
in CallJavascriptResult.hx:
```
public function addInlineJs( js:String ):CallJavascriptResult<T> {
		scripts.push( '<script id="ufrontScript" type="text/javascript">$js</script>' );
		return this;
}

public function addJsScript( path:String ):CallJavascriptResult<T> {
	scripts.push( '<script id="ufrontScript" type="text/javascript" src="$path"></script>' );
	return this;
}
```

and check this attribute in HttpResponse (js):
```
document.find("script").each(function(node) {
	if (node.attr("id") == "ufrontScript") {
	...
```

using it in the controller
```
return new ViewResult(args).addJsScriptToResult("path/to/script");
```

**Comment by kevinresol** [comment]
Updated. Only script tags with `uf-reload` attribute will re-run

Examples:
```html
<script uf-reload>console.log("test");</script>
<script uf-reload src="app.js"></script>
```

**Comment by kevinresol** [comment]
Next: Need to add one more parameter (`reload:Bool`) to `CallJSResult`
```haxe
public function addInlineJs( js:String, reload:Bool ):CallJavascriptResult<T>;
public function addJsScript( path:String, reload:Bool ):CallJavascriptResult<T>;
```

**Comment by MichaPau** [comment]
+1 looks like a nice solution

**Pull request closed without merging**
