### PR TITLE
fix binary response on nodejs

### PR DESCRIPTION
**Pull request by kevinresol**
a quick and dirty solution for #36

I still need to figure out if it is necessary to do the conversion `var buffer = new js.node.Buffer([for(i in 0...bytes.length) bytes.get(i)]);`

### CODE REVIEW

**Comment by kevinresol** [comment]
Because I am using js-kit and I have to disable hxnodejs due to some duplicated definitions of the externs. Hopefully js-kit will migrate to hxnodejs soon. cc @clemos

**Comment by clemos** [comment]
We're working on it :)

**Comment by clemos** [comment]
As for your issue, `hxnodejs` has some `Bytes` to `Buffer` conversion functions that I think may help: https://github.com/HaxeFoundation/hxnodejs/blob/master/src/js/node/buffer/Buffer.hx#L482-L492

**Comment by kevinresol** [comment]
thanks @clemos for pointing that conversion method! but at the moment I am still sticking with js-kit for Mongoose. I may come back to this later when js-kit fully migrated to hxnodejs.

**Comment by kevinresol** [comment]
@jasononeil please just keep this open for a moment.

**Comment by kevinresol** [comment]
Closed this, see #42

**Pull request closed without merging**
